### PR TITLE
Fix toJson() methods of BaseDataObject-implementing classes…

### PR DESCRIPTION
**Pull request by xkr47**
… that have a superclass.

### CODE REVIEW

**Comment by xkr47** [comment]
I noticed that idleTimeout and other fields of HttpServerOptions had no effect when creating a server.

The ceylon source said "Generated from" but wasn't able to build the project using maven so gave up and just patched the source, to at least communicate the idea. The maven error was:

    [INFO] --- ceylon-maven-plugin:1.2.0:import-dependency (import-dependencies) @ vertx-lang-ceylon ---
    tammikuuta 18, 2016 10:24:54 IP. org.sonatype.guice.bean.reflect.Logs$JULSink warn
    WARNING: Error injecting: com.redhat.ceylon.maven.CeylonImportDependencyMojo
    com.google.inject.ProvisionException: Guice provision errors:

    1) No implementation for org.eclipse.aether.RepositorySystem was bound.
      while locating com.redhat.ceylon.maven.CeylonImportDependencyMojo

Some tests would probably be good as well but for the above reason..

**Comment by vietj** [comment]
what's your maven version ?

**Comment by xkr47** [comment]
3.0.5 apparently.. I'll try a newer one.

**Comment by vietj** [comment]
btw you should not patch the source code but instead the source code generator here https://github.com/vert-x3/vertx-lang-ceylon/blob/master/vertx-lang-ceylon/src/main/resources/vertx-ceylon/template/ceylon-dataobject.templ

**Comment by vietj** [comment]
try at least 3.2 event 3.3

**Comment by xkr47** [comment]
3.3.9 and compiles fine.

ok found the `toJson` in the file you referred to.. should I change it to somehow figure out whether to start with `JsonObject()` or `super.toJson()` ; or should I rather make it iterate all props including superclasses in toJson()?

**Comment by vietj** [comment]
I thin it should check if the parent class exists or not and call super.toJson() if it exists.

the parent super class can be checked with `concreteSuperClass` I think (it must be used in other places I think, check)

**Comment by vietj** [comment]
codegen documentation in case you want to have a look at it : https://github.com/vert-x3/vertx-codegen/blob/master/src/main/asciidoc/java/index.adoc

**Comment by xkr47** [comment]
ok thanks! should I force-push the new commit to this same pull request, taking out the currently proposed commit?

thanks for the documentation tip :)

**Comment by vietj** [comment]
actually it is : concreteSuperType (just looked at the doc I linked)

**Comment by vietj** [comment]
make a new PR rather and please, sign the Eclipse CLA (explained here https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md)

**Comment by xkr47** [comment]
"Sign-off" your commits (NOTE! This is only necessary if contributing to the vertx-core project)

is this a "vertx-core" project?

**Comment by vietj** [comment]
you should sign your commits, even though we don't require it yet for non vertx-core, we would at some point ask you when the project would be moved to Eclipse. so that would save us some time later and make things clean.

**Comment by vietj** [comment]
lot of would in my comment

**Comment by xkr47** [comment]
anywhere we can chat? having trouble compiling..

**Comment by vietj** [comment]
IRC freenode #vertx

**Comment by vietj** [comment]
ping temporalfox on IRC

**Comment by xkr47** [comment]
Force-repushed initial commit amended with Signed-off-by and added further changes and unit tests according to suggestion. Decided to stick with the original PR tho. :)

For some reason `concreteSuperType` did not work but `superType` did. The latter was also used in the `extends` clause so sounded legit to me..

**Comment by vietj** [comment]
thanks

**Pull request merged**
